# Generated by Django 2.0.2 on 2018-12-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20181128_1337'),
        ('stocks', '0005_auto_20181202_1551'),
    ]

    operations = [
    ]
